name: Release

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: cargo test --release
      - name: Build
        run: cargo build --release
      - name: Upload portable executable
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: |
            target/release/*.exe

